import type { Terapeuta, Plano, BlogPost } from "./types";

const U = (id: string) =>
  `https://images.unsplash.com/${id}?w=640&q=80&auto=format&fit=crop`;

export const ESPECIALIDADES = [
  "Ansiedade",
  "Depressão",
  "Relacionamentos",
  "Luto",
  "Autoconhecimento",
  "Estresse e Burnout",
  "Traumas",
  "Autoestima",
  "Transtornos alimentares",
  "Sexualidade",
  "Maternidade",
  "Espiritualidade",
];

export const ABORDAGENS = [
  "Psicanálise",
  "Terapia Cognitivo-Comportamental",
  "Humanista",
  "Gestalt-terapia",
  "Sistêmica",
  "Junguiana",
  "Fenomenológica",
];

export const IDIOMAS = ["Português", "Inglês", "Espanhol", "Libras", "Italiano"];

export const PUBLICOS = [
  "Infantil",
  "Adolescente",
  "Adulto",
  "Idoso",
  "Casal",
  "Familiar",
] as const;

export const PLANOS: Plano[] = [
  {
    tier: "inicial",
    nome: "Inicial",
    preco: 39,
    descricao: "Para começar a sua presença digital com o essencial.",
    recursos: [
      "Perfil na plataforma",
      "Informações pessoais",
      "Sobre (200 caracteres)",
      "Formação e idiomas",
      "Valores e formas de atendimento",
      "Aparece nas buscas",
    ],
  },
  {
    tier: "completo",
    nome: "Completo",
    preco: 89,
    descricao: "Todos os recursos para se destacar e receber pacientes.",
    recursos: [
      "Tudo do plano Inicial",
      "Perfil completo e detalhado",
      "Galeria e vídeo de apresentação",
      "Avaliações de pacientes",
      "Gestão de agenda e solicitações",
      "Estatísticas do perfil",
    ],
    destaque: true,
  },
  {
    tier: "premium",
    nome: "Premium",
    preco: 149,
    descricao: "Completo + Landing Page Premium com URL própria.",
    recursos: [
      "Tudo do plano Completo",
      "Landing Page Premium exclusiva",
      "URL própria dentro da plataforma",
      "FAQ personalizado",
      "Destaque nas buscas",
      "Suporte prioritário",
    ],
  },
];

export const TERAPEUTAS: Terapeuta[] = [
  {
    id: "1",
    slug: "ana-beatriz-moraes",
    nome: "Ana Beatriz Moraes",
    titulo: "Psicanalista clínica",
    foto: U("photo-1594824476967-48c8b964273f"),
    cidade: "São Paulo",
    estado: "SP",
    modalidades: ["Online", "Presencial"],
    especialidades: ["Ansiedade", "Autoconhecimento", "Relacionamentos"],
    abordagens: ["Psicanálise"],
    idiomas: ["Português", "Inglês"],
    publicos: ["Adulto", "Casal"],
    preco: 180,
    sobre:
      "Escuta a sua história com acolhimento e profundidade, ajudando você a compreender padrões e retomar o sentido da sua jornada.",
    formacao: [
      "Psicanálise — Instituto Sedes Sapientiae",
      "Pós em Clínica Psicanalítica — PUC-SP",
    ],
    plano: "premium",
    destaque: true,
    agendaAberta: true,
    convenio: false,
    primeiraGratuita: true,
    atendimentoSocial: true,
    notaMedia: 4.9,
    totalAvaliacoes: 42,
    video: "https://www.youtube.com/embed/inpok4MKVLM",
    instagram: "anabeatriz.psi",
    whatsapp: "5511999990001",
    crp: "CRP 06/123456",
    avaliacoes: [
      {
        id: "a1",
        paciente: "Marina L.",
        nota: 5,
        comentario:
          "A Ana me ajudou a entender questões que eu carregava há anos. Espaço seguro e acolhedor.",
        data: "2026-05-12",
      },
      {
        id: "a2",
        paciente: "Rafael C.",
        nota: 5,
        comentario: "Profissional excelente, escuta atenta e muito humana.",
        data: "2026-04-28",
      },
    ],
  },
  {
    id: "2",
    slug: "carlos-eduardo-lima",
    nome: "Carlos Eduardo Lima",
    titulo: "Psicanalista",
    foto: U("photo-1612349317150-e413f6a5b16d"),
    cidade: "Rio de Janeiro",
    estado: "RJ",
    modalidades: ["Online"],
    especialidades: ["Depressão", "Estresse e Burnout", "Autoestima"],
    abordagens: ["Psicanálise", "Fenomenológica"],
    idiomas: ["Português"],
    publicos: ["Adulto", "Idoso"],
    preco: 150,
    sobre:
      "Acompanho adultos que buscam sair do piloto automático e reconstruir uma relação mais gentil consigo mesmos.",
    formacao: ["Formação em Psicanálise — CEP", "Bacharel em Psicologia — UFRJ"],
    plano: "completo",
    destaque: true,
    agendaAberta: true,
    convenio: true,
    primeiraGratuita: false,
    atendimentoSocial: false,
    notaMedia: 4.8,
    totalAvaliacoes: 31,
    instagram: "carloslima.psi",
    whatsapp: "5521999990002",
    crp: "CRP 05/654321",
    avaliacoes: [
      {
        id: "b1",
        paciente: "Juliana P.",
        nota: 5,
        comentario: "Mudou minha forma de lidar com o trabalho e a ansiedade.",
        data: "2026-06-01",
      },
    ],
  },
  {
    id: "3",
    slug: "fernanda-souza",
    nome: "Fernanda Souza",
    titulo: "Psicóloga · TCC",
    foto: U("photo-1573496359142-b8d87734a5a2"),
    cidade: "Belo Horizonte",
    estado: "MG",
    modalidades: ["Online", "Presencial"],
    especialidades: ["Ansiedade", "Transtornos alimentares", "Autoestima"],
    abordagens: ["Terapia Cognitivo-Comportamental"],
    idiomas: ["Português", "Espanhol"],
    publicos: ["Adolescente", "Adulto"],
    preco: 130,
    sobre:
      "Trabalho com ferramentas práticas da TCC para você lidar com a ansiedade e reencontrar equilíbrio no dia a dia.",
    formacao: ["Especialização em TCC — WP", "Psicologia — UFMG"],
    plano: "premium",
    destaque: true,
    agendaAberta: true,
    convenio: false,
    primeiraGratuita: true,
    atendimentoSocial: true,
    notaMedia: 5.0,
    totalAvaliacoes: 58,
    video: "https://www.youtube.com/embed/inpok4MKVLM",
    instagram: "fernanda.psi",
    whatsapp: "5531999990003",
    crp: "CRP 04/222333",
    avaliacoes: [
      {
        id: "c1",
        paciente: "Beatriz M.",
        nota: 5,
        comentario: "Didática, acolhedora e muito competente. Recomendo demais!",
        data: "2026-05-20",
      },
      {
        id: "c2",
        paciente: "Lucas F.",
        nota: 5,
        comentario: "As primeiras sessões já fizeram muita diferença.",
        data: "2026-06-10",
      },
    ],
  },
  {
    id: "4",
    slug: "roberto-menezes",
    nome: "Roberto Menezes",
    titulo: "Psicanalista · Casal e Família",
    foto: U("photo-1559839734-2b71ea197ec2"),
    cidade: "Curitiba",
    estado: "PR",
    modalidades: ["Presencial", "Online"],
    especialidades: ["Relacionamentos", "Luto"],
    abordagens: ["Psicanálise", "Sistêmica"],
    idiomas: ["Português", "Inglês"],
    publicos: ["Casal", "Familiar", "Adulto"],
    preco: 200,
    sobre:
      "Atendo casais e famílias que desejam reconstruir vínculos e melhorar a comunicação com respeito e cuidado.",
    formacao: ["Terapia de Família — Familiae", "Psicanálise — SBPdePA"],
    plano: "completo",
    destaque: false,
    agendaAberta: false,
    convenio: false,
    primeiraGratuita: false,
    atendimentoSocial: false,
    notaMedia: 4.7,
    totalAvaliacoes: 19,
    whatsapp: "5541999990004",
    crp: "CRP 08/445566",
    avaliacoes: [
      {
        id: "d1",
        paciente: "Casal A. & R.",
        nota: 5,
        comentario: "Salvou nosso casamento. Gratidão imensa.",
        data: "2026-03-15",
      },
    ],
  },
  {
    id: "5",
    slug: "patricia-nogueira",
    nome: "Patrícia Nogueira",
    titulo: "Psicóloga · Junguiana",
    foto: U("photo-1580489944761-15a19d654956"),
    cidade: "Porto Alegre",
    estado: "RS",
    modalidades: ["Online"],
    especialidades: ["Autoconhecimento", "Espiritualidade", "Maternidade"],
    abordagens: ["Junguiana"],
    idiomas: ["Português"],
    publicos: ["Adulto", "Familiar"],
    preco: 160,
    sobre:
      "Convido você a um mergulho no autoconhecimento, integrando símbolos, sonhos e a sua história de vida.",
    formacao: ["Psicologia Analítica — IJRS", "Psicologia — PUCRS"],
    plano: "inicial",
    destaque: false,
    agendaAberta: true,
    convenio: false,
    primeiraGratuita: true,
    atendimentoSocial: true,
    notaMedia: 4.9,
    totalAvaliacoes: 27,
    whatsapp: "5551999990005",
    crp: "CRP 07/778899",
    avaliacoes: [
      {
        id: "e1",
        paciente: "Camila S.",
        nota: 5,
        comentario: "Um processo lindo de reencontro comigo mesma.",
        data: "2026-04-05",
      },
    ],
  },
  {
    id: "6",
    slug: "andre-tavares",
    nome: "André Tavares",
    titulo: "Psicanalista clínico",
    foto: U("photo-1607990281513-2c110a25bd8c"),
    cidade: "São Paulo",
    estado: "SP",
    modalidades: ["Online", "Presencial"],
    especialidades: ["Traumas", "Ansiedade", "Estresse e Burnout"],
    abordagens: ["Psicanálise"],
    idiomas: ["Português", "Inglês", "Italiano"],
    publicos: ["Adulto"],
    preco: 170,
    sobre:
      "Especialista em traumas e ansiedade, ofereço um espaço seguro para elaborar experiências difíceis no seu tempo.",
    formacao: ["Psicanálise — Instituto Sedes", "Mestrado em Psicologia — USP"],
    plano: "completo",
    destaque: false,
    agendaAberta: true,
    convenio: true,
    primeiraGratuita: false,
    atendimentoSocial: false,
    notaMedia: 4.8,
    totalAvaliacoes: 36,
    instagram: "andretavares.psi",
    whatsapp: "5511999990006",
    crp: "CRP 06/998877",
    avaliacoes: [
      {
        id: "f1",
        paciente: "Diego R.",
        nota: 5,
        comentario: "Profundo, respeitoso e transformador.",
        data: "2026-05-30",
      },
    ],
  },
  {
    id: "7",
    slug: "juliana-castro",
    nome: "Juliana Castro",
    titulo: "Psicóloga · Infantil",
    foto: U("photo-1544005313-94ddf0286df2"),
    cidade: "Salvador",
    estado: "BA",
    modalidades: ["Presencial", "Online"],
    especialidades: ["Ansiedade", "Autoestima"],
    abordagens: ["Gestalt-terapia", "Humanista"],
    idiomas: ["Português"],
    publicos: ["Infantil", "Adolescente"],
    preco: 120,
    sobre:
      "Atendo crianças e adolescentes com uma escuta lúdica e afetuosa, envolvendo a família no processo.",
    formacao: ["Gestalt-terapia — IGT", "Psicologia — UFBA"],
    plano: "inicial",
    destaque: false,
    agendaAberta: true,
    convenio: false,
    primeiraGratuita: true,
    atendimentoSocial: true,
    notaMedia: 5.0,
    totalAvaliacoes: 22,
    whatsapp: "5571999990007",
    crp: "CRP 03/112233",
    avaliacoes: [
      {
        id: "g1",
        paciente: "Mãe do Théo",
        nota: 5,
        comentario: "Meu filho adora as sessões. Evolução visível.",
        data: "2026-06-08",
      },
    ],
  },
  {
    id: "8",
    slug: "marcos-vieira",
    nome: "Marcos Vieira",
    titulo: "Psicanalista",
    foto: U("photo-1551836022-d5d88e9218df"),
    cidade: "Recife",
    estado: "PE",
    modalidades: ["Online"],
    especialidades: ["Depressão", "Sexualidade", "Autoconhecimento"],
    abordagens: ["Psicanálise"],
    idiomas: ["Português", "Espanhol"],
    publicos: ["Adulto", "Idoso"],
    preco: 140,
    sobre:
      "Ofereço uma escuta livre de julgamentos para questões de identidade, sexualidade e sentido de vida.",
    formacao: ["Psicanálise — Círculo Psicanalítico", "Psicologia — UFPE"],
    plano: "completo",
    destaque: false,
    agendaAberta: false,
    convenio: false,
    primeiraGratuita: false,
    atendimentoSocial: true,
    notaMedia: 4.7,
    totalAvaliacoes: 15,
    instagram: "marcosvieira.psi",
    whatsapp: "5581999990008",
    crp: "CRP 02/334455",
    avaliacoes: [
      {
        id: "h1",
        paciente: "Anônimo",
        nota: 5,
        comentario: "Me senti acolhido como nunca antes.",
        data: "2026-05-18",
      },
    ],
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "como-escolher-terapeuta",
    titulo: "Como escolher o terapeuta ideal para você",
    resumo:
      "O vínculo terapêutico é o coração do processo. Veja como identificar o profissional certo para a sua jornada.",
    categoria: "Guia",
    autor: "Equipe MyTerapie",
    data: "2026-07-01",
    leitura: "5 min",
    capa: U("photo-1573497019940-1c28c88b4f3e"),
    conteudo: [
      "Escolher um terapeuta é uma decisão pessoal e importante. Não existe um profissional 'melhor' de forma absoluta — existe aquele que faz mais sentido para o seu momento.",
      "Considere a abordagem, a especialidade, a modalidade (online ou presencial) e, sobretudo, como você se sente na primeira conversa. O vínculo é o que sustenta o processo.",
      "Na MyTerapie, você pode filtrar por especialidade, abordagem, idioma e valores, além de ler avaliações de outros pacientes antes de solicitar um agendamento.",
    ],
  },
  {
    slug: "psicanalise-no-dia-a-dia",
    titulo: "Psicanálise no dia a dia: o que esperar das primeiras sessões",
    resumo:
      "Desmistificando o divã: como funciona a psicanálise e por que ela continua tão atual.",
    categoria: "Psicanálise",
    autor: "Ana Beatriz Moraes",
    data: "2026-06-20",
    leitura: "7 min",
    capa: U("photo-1512438248247-f0f2a5a8b7f0"),
    conteudo: [
      "A psicanálise parte de uma ideia simples e poderosa: falar transforma. Ao colocar em palavras aquilo que sentimos, começamos a compreender padrões que antes se repetiam em silêncio.",
      "As primeiras sessões são um espaço de conhecimento mútuo. Não há respostas prontas — há escuta, tempo e cuidado.",
      "Com constância, a análise ajuda a construir uma relação mais livre com a própria história.",
    ],
  },
  {
    slug: "ansiedade-e-autocuidado",
    titulo: "Ansiedade e autocuidado: pequenos passos que fazem diferença",
    resumo:
      "Estratégias simples e baseadas em evidências para cuidar da mente na correria da vida moderna.",
    categoria: "Bem-estar",
    autor: "Fernanda Souza",
    data: "2026-06-05",
    leitura: "4 min",
    capa: U("photo-1499209974431-9daddcb0d909"),
    conteudo: [
      "A ansiedade faz parte da vida, mas quando se torna constante, pede cuidado. O primeiro passo é reconhecê-la sem se julgar.",
      "Rotinas de sono, respiração consciente e pausas ao longo do dia ajudam a regular o sistema nervoso.",
      "A terapia oferece um espaço para entender as raízes da ansiedade e desenvolver recursos duradouros.",
    ],
  },
];

export function getTerapeuta(slug: string) {
  return TERAPEUTAS.find((t) => t.slug === slug);
}

export function getPost(slug: string) {
  return BLOG_POSTS.find((p) => p.slug === slug);
}
